---
  
- name: Install MySQL
  hosts: frncesnapora01.sd.galderma.com
  tasks:
    - name: Install the MySQL repo 
      yum: 
        name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm 
        state: present  
 
    - name: Override variables for MySQL (RedHat) 
      set_fact: 
        mysql_daemon: mysqld 
        mysql_packages: ['mysql-server'] 
        mysql_log_error: /var/lib/mysql/error.log 
        mysql_syslog_tag: mysqld 
        mysql_pid_file: /var/run/mysqld/mysqld.pid 
        mysql_socket: /var/lib/mysql/mysql.sock       

- name: Configure MySQL
  hosts: frncesnapora01.sd.galderma.com
  tasks:
    - name: Configure my.cnf
      copy: src=./files/my.cnf
            dest=/etc/mysql/my.cnf
            owner=root
            group=root
            mode=0640
      notify:
        - restart mysql
    
    - name: Add mysql-user
      mysql_user: name=mysql_service
                  password=12345
                  priv=*.*:ALL
                  state=present
      notify:
        - start mysql

  handlers:
    - name: start mysql
      service: name=mysql
               enabled=yes
               state=started
    - name: restart mysql
      service: name=mysql
               enabled=yes
               state=restarted



# /sbin/iptables -A INPUT -i eth0 -s 192.168.33.0/24 -p tcp --destination-port 3306 -j ACCEPT
# service iptables save
