---
  
- name: Install MySQL
  hosts: frncesnapora01.sd.galderma.com
  vars:
    mysql_root_password: daniel
  tasks:
     
    - name: Install MySQL 5.7
      yum: name=mysql update_cache=yes state=present      
 
    - name: start mysql
      service: name=mysqld
               enabled=yes
               state=started
 
    - name: update mysql root password for all root accounts
      mysql_user: root
      host: localhost
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    
    - name: install required python MySQLdb lib to create databases and users
      yum: name={{item}} state=present
      with_items:
        - gcc-c++
        - MySQL-python
        
    - name: create db user
      mysql_user: name=testdb state=present login_user=root login_password="{{ mysql_root_password }}" 
      
    - name: create mysql database
      mysql_db: name=testdb state=present
      
    - name: bind mysql remote address
      ini_file: dest=/etc/my.cnf
            section=mysqld
            option=bind-address
            value={{item}}
      with_items: mysql.bind
      
    - name: start mysql
      service: name=mysqld
               enabled=yes
               state=restarted  
