---
  
- name: Install MySQL
  hosts: frncesnapora01.sd.galderma.com
  tasks:
    - name: Install MySQL repo
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present

    - name: Install MySQL 5.7
      yum: name=mysql update_cache=yes state=present
      with_items:
        - mysql-community-server
        - MySQL-python 

    - name: Start the MySQL service
      service:
        name: mysql
        state: started
        enabled: true

    - name: Configure the root credentials
      action: command mysqladmin -u root -p daniel
