---
- name: Install MySQL
  hosts: frncesnapora01.sd.galderma.com
  
  tasks:
    - name: Install MySQL
      action: yum name=$item state=present
      with_items:
        - MySQL-python
        - mysql
        - mysql-server

    - name: Start the MySQL service
      action: service name=mysqld state=started

    - name: Configure the root credentials
      action: command mysqladmin -u root -p daniel
