---
  
- name: Install MySQL
  hosts: frncesnapora01.sd.galderma.com
  vars:
    mysql_root_password: daniel
    
  tasks:
    - name: Install MySQL repo
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present
      
    - name: Install MySQL 5.7
      yum: pkg={{ item }}
      with_items:
        - mysql-community-server
        - mysql
        - MySQL-python
        
    - name: start up the mysql service  
      shell: |
        systemctl stop mysqld
        systemctl set-environment MYSQLD_OPTS="--skip-grant-tables"
        systemctl start mysqld
    
    - name: Set new password for root
      command: >        
        "mysql UPDATE mysql.user SET authentication_string = PASSWORD('daniel') WHERE User = 'root' AND Host = 'localhost'"
 
    - name: start mysql
      service: name=mysqld
               enabled=yes
               state=restarted
    
    
    - name: install required python MySQLdb lib to create databases and users
      yum: name={{item}} state=present
      with_items:
        - gcc-c++
        - MySQL-python
        
    - name: create db
      mysql_user: name=testdb state=present login_user=root login_password="{{ mysql_root_password }}" 
              
    - name: bind mysql remote address
      ini_file: dest=/etc/my.cnf
            section=mysqld
            option=bind-address
            value={{item}}
      with_items: mysql.bind
      
    - name: start mysql
      service: name=mysqld
               enabled=yes
               state=restarted  
