---
  
- name: Install MySQL
  hosts: frncesnapora01.sd.galderma.com
  tasks:
    - name: Install MySQL repo
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present
 
    - name: Install MySQL 5.7
      yum: pkg={{ item }}
      with_items:
        - mysql-community-server
        - MySQL-python     

  handlers:
    - name: start mysql
      hosts: frncesnapora01.sd.galderma.com
      service: name=mysql
               enabled=yes
               state=started
      
- name: Configure MySQL
  hosts: frncesnapora01.sd.galderma.com
  tasks:
    - name: Add mysql-user
      mysql_user: name=daniel
                  password=daniel
                  priv=*.*:ALL
                  state=present
                  
    - name: Configure my.cnf
      copy: src=./files/my.cnf
            dest=/root/.my.cnf
            owner=root
            group=root
            mode=0640
      notify:
        - restart mysql 
       
  handlers:
    - name: start mysql
      service: name=mysql
               enabled=yes
               state=started
    - name: restart mysql
      service: name=mysql
               enabled=yes
               state=restarted



# /sbin/iptables -A INPUT -i eth0 -s 192.168.33.0/24 -p tcp --destination-port 3306 -j ACCEPT
# service iptables save
