---
  
- name: Install MySQL
  hosts: frncesnapora01.sd.galderma.com
  vars:
    mysql_root_password: daniel
    
  tasks:
    - name: Install MySQL repo
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present
      
    - name: Install MySQL 5.7
      yum: pkg={{ item }}
      with_items:
        - mysql-community-server
        - mysql
        - MySQL-python
        
    - name: stop mysql
      service: name=mysqld
               enabled=no
               state=stopped
        
    - name: Set variable      
      shell: systemctl set-environment MYSQLD_OPTS="--skip-grant-tables"
    
    - name: start mysql
      service: name=mysqld
               enabled=yes
               state=started
               
    - name: Set new pass for Root
      shell: mysql -u root -e "UPDATE mysql.user SET authentication_string = PASSWORD('daniel') WHERE User = 'root' AND Host = 'localhost'"; flush privileges; UPDATE user SET Grant_priv = 1, Super_priv = 1 WHERE user = 'root';
       
 
    - name: restart mysql
      service: name=mysqld
               enabled=yes
               state=restarted
    
    
    - name: install required python MySQLdb lib to create databases and users
      yum: name={{item}} state=present
      with_items:
        - gcc-c++
        - MySQL-python
        
    - name: create db
      mysql_user: name=testdb state=present login_user=root login_password="{{ mysql_root_password }}" 
              
    - name: start mysql
      service: name=mysqld
               enabled=yes
               state=restarted
